# Generated by Django 4.2 on 2024-01-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tgbot", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brand",
            name="category",
        ),
        migrations.AddField(
            model_name="brand",
            name="category",
            field=models.ManyToManyField(to="tgbot.category"),
        ),
    ]
