# Generated by Django 4.2 on 2024-01-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tgbot", "0002_news_userbot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbot",
            name="user_id",
            field=models.BigIntegerField(unique=True, verbose_name="USER ID"),
        ),
    ]
