# Generated by Django 4.2 on 2024-01-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tgbot", "0002_remove_brand_category_brand_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="category",
            field=models.ManyToManyField(related_name="brands", to="tgbot.category"),
        ),
    ]
